
project_id = "bibaxlvbkxhrkurbhxcb"

[[functions]]
name = "import-profiles"
verify_jwt = false

[[functions]]
name = "import-bird-species"
verify_jwt = false

[[functions]]
name = "download-audio"
verify_jwt = false

[[functions]]
name = "import-bird-sounds"
verify_jwt = false

[[functions]]
name = "identify-bird"
verify_jwt = false

[[functions]]
name = "transcribe-audio"
verify_jwt = false

[[functions]]
name = "send-email"
verify_jwt = false

[[functions]]
name = "create-backup"
verify_jwt = false

[[functions]]
name = "resend-webhook"
verify_jwt = false

[[functions]]
name = "send-conversation"
verify_jwt = false
