
project_id = "bibaxlvbkxhrkurbhxcb"

[functions.import-profiles]
verify_jwt = false

[functions.import-bird-species]
verify_jwt = false

[functions.download-audio]
verify_jwt = false

[functions.import-bird-sounds]
verify_jwt = false

[functions.identify-bird]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.create-backup]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.send-conversation]
verify_jwt = false
