
project_id = "bibaxlvbkxhrkurbhxcb"

[functions.import-bird-species]
verify_jwt = false

[functions.download-audio]
verify_jwt = false

[functions.send-email]
verify_jwt = false
import_map = "./functions/send-email/import_map.json"

