// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bibaxlvbkxhrkurbhxcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpYmF4bHZia3hocmt1cmJoeGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzE3OTQsImV4cCI6MjA1MjU0Nzc5NH0.4Dkyc7zYe-1S8o5-ss7iZ1zKKWNIgvdQra9aLxg83tY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);